CREATE DATABASE VULN_NETFRAMEWORK;
GO
USE VULN_NETFRAMEWORK;
CREATE TABLE VULN_NETFRAMEWORK_USER (ID INT, NAME NVARCHAR(50), ROLE NVARCHAR(20));
INSERT INTO VULN_NETFRAMEWORK_USER VALUES(1, 'admin','admin');
GO